// Helpers for the GitHub-Pages SPA fallback. Pure module — no `react-native`
// or DOM imports — so it can be unit-tested from plain Node.
//
// Why this exists: the app is a client-only SPA (`expo.web.output: "single"`),
// so `expo export` emits ONE route-agnostic `index.html` that renders every
// route on the client. GitHub Pages is a static host: a request for a path
// with no matching file (every dynamic route, e.g. `/collection/<id>`) is
// answered with `404.html`. The canonical fix is to make `404.html` a byte
// copy of the SPA shell so the deep link boots the app directly — one
// document, one navigation, NO redirect/replaceState dance (that dance, plus
// the old `output: "static"` per-route prerender, is what made iOS Safari
// reload-loop into "a problem repeatedly occurred").
//
// GitHub Pages still serves that shell with HTTP status 404. A static 404
// *body* that renders and stays put does not trip Safari's loop detector
// (only redirect/reload chains do), but the service worker below upgrades it
// anyway: once installed it answers a deep-link navigation by fetching the
// fresh shell and returning it with 200, so warm reloads never surface a 404.

export const SPA_SW_REGISTER_MARKER = "data-spa-sw";
export const SERVICE_WORKER_FILENAME = "sw.js";

export function normalizeSpaBaseUrl(baseUrl: string): string {
  let b = (baseUrl ?? "").trim();
  if (b === "" || b === "/") return "/";
  if (!b.startsWith("/")) b = "/" + b;
  if (!b.endsWith("/")) b += "/";
  return b;
}

/**
 * Service-worker source. `version` should change whenever the deployed bundle
 * changes (the build script passes a hash of the patched index.html) so a
 * redeploy installs a fresh SW and evicts the old offline cache.
 *
 * Only same-origin GET navigations under the base are intercepted, and the
 * strategy is network-first so online users always get current content:
 * - 2xx  → return it; refresh the offline shell when it's the shell itself.
 * - 404  → a dynamic route GitHub Pages can't resolve: fetch the *fresh*
 *          canonical shell (BASE) and return that with 200 — never a cached,
 *          possibly-stale shell, so it can't reference since-deleted JS
 *          chunks and loop. Cached shell is the offline-only last resort.
 * - throw → offline; serve the cached shell if we have one.
 * Asset requests pass straight through to the network (not intercepted).
 */
export function buildServiceWorker(baseUrl: string, version: string): string {
  const base = normalizeSpaBaseUrl(baseUrl);
  const baseLiteral = JSON.stringify(base);
  const cacheName = JSON.stringify("collectables-spa-" + (version || "dev"));
  return `// Generated by scripts/build-spa-fallback.ts — do not edit by hand.
var CACHE = ${cacheName};
var BASE = ${baseLiteral};
var SHELL = BASE;

self.addEventListener("install", function (event) {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE).then(function (cache) {
      return cache.add(new Request(SHELL, { cache: "reload" }));
    }).catch(function () {})
  );
});

self.addEventListener("activate", function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys.map(function (k) {
          return k === CACHE ? null : caches.delete(k);
        })
      );
    }).then(function () {
      return self.clients.claim();
    })
  );
});

function freshShell() {
  return fetch(new Request(SHELL, { cache: "reload" })).then(function (res) {
    if (res && res.ok) {
      var copy = res.clone();
      caches.open(CACHE).then(function (cache) {
        cache.put(SHELL, copy);
      }).catch(function () {});
      return res;
    }
    return caches.match(SHELL);
  }).catch(function () {
    return caches.match(SHELL);
  });
}

self.addEventListener("fetch", function (event) {
  var req = event.request;
  if (req.method !== "GET") return;
  if (req.mode !== "navigate") return;
  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname.indexOf(BASE) !== 0) return;

  // Real static pages that exist on GitHub Pages next to the SPA (the
  // privacy policy) must never be answered with the app shell — let the
  // network serve them, even on warm clients with the SW installed.
  if (
    url.pathname === BASE + "privacy" ||
    url.pathname.indexOf(BASE + "privacy/") === 0
  ) {
    return;
  }

  // For the shell itself: network-first, refresh the cached copy on success.
  if (url.pathname === BASE) {
    event.respondWith(
      fetch(req).then(function (res) {
        if (res && res.ok) {
          var copy = res.clone();
          caches.open(CACHE).then(function (cache) {
            cache.put(SHELL, copy);
          }).catch(function () {});
        }
        return res;
      }).catch(function () {
        return caches.match(SHELL).then(function (cached) {
          return cached || Response.error();
        });
      })
    );
    return;
  }

  // For every deep-link navigation under BASE: serve the shell directly. Never
  // probe the dynamic route — GitHub Pages can't resolve it and we'd just get
  // a 404 back. The probe was producing a "phantom" failed network row per
  // navigation in DevTools and adding latency; iOS Safari counted the 404 as
  // a navigation problem and could trip the "A problem repeatedly occurred"
  // detector on warm reloads.
  event.respondWith(
    freshShell().then(function (shell) {
      return shell || caches.match(SHELL).then(function (cached) {
        return cached || Response.error();
      });
    })
  );
});
`;
}

export function injectServiceWorkerRegistration(
  html: string,
  baseUrl: string,
): string {
  if (html.includes(SPA_SW_REGISTER_MARKER)) return html;
  const base = normalizeSpaBaseUrl(baseUrl);
  const swUrl = JSON.stringify(base + SERVICE_WORKER_FILENAME);
  const scope = JSON.stringify(base);
  const script = `<script ${SPA_SW_REGISTER_MARKER}>
(function () {
  if (!("serviceWorker" in navigator)) return;
  var h = location.hostname;
  var secure = location.protocol === "https:" || h === "localhost" || h === "127.0.0.1";
  if (!secure) return;
  window.addEventListener("load", function () {
    try {
      navigator.serviceWorker.register(${swUrl}, { scope: ${scope} }).catch(function () {});
    } catch (e) {}
  });
})();
</script>`;
  if (html.includes("</head>")) {
    return html.replace("</head>", `${script}</head>`);
  }
  return script + html;
}
