// Helpers that generate the GitHub-Pages SPA fallback artefacts. Pure module —
// no `react-native` or DOM imports — so it can be unit-tested from plain Node.
//
// Why this exists: GitHub Pages serves `404.html` with HTTP status 404 for any
// path it cannot resolve to a real file. Dynamic Expo Router routes like
// `/collection/[id]` never resolve, so a deep link returns 404 even though the
// shipped HTML boots the SPA correctly. iOS Safari reacts to that 404 status
// by retrying the page; after three retries it gives up with "A problem
// repeatedly occurred". The redirect dance below sends the browser to the
// baseUrl (which serves with 200) and restores the URL on the next page load.
//
// The redirect is the *cold-start* path (no service worker yet). Once the
// service worker from `buildServiceWorker` is installed it intercepts every
// in-app navigation: a deep-link reload like `/collection/<id>` returns the
// GitHub-Pages 404, the SW swallows that and serves the cached app shell with
// HTTP 200 instead — so the 404 status never reaches iOS Safari and there is
// no redirect flash on reload. Network-first keeps online users on fresh
// content; the cached shell is only used to rescue the 404/offline case.

export const SPA_REDIRECT_STORAGE_KEY = "collectables:spa-redirect";
export const SPA_RESTORE_SCRIPT_MARKER = "data-spa-restore";
export const SPA_SW_REGISTER_MARKER = "data-spa-sw";
export const SERVICE_WORKER_FILENAME = "sw.js";

export function normalizeSpaBaseUrl(baseUrl: string): string {
  let b = (baseUrl ?? "").trim();
  if (b === "" || b === "/") return "/";
  if (!b.startsWith("/")) b = "/" + b;
  if (!b.endsWith("/")) b += "/";
  return b;
}

export function build404Html(baseUrl: string): string {
  const base = normalizeSpaBaseUrl(baseUrl);
  const storageKey = JSON.stringify(SPA_REDIRECT_STORAGE_KEY);
  const target = JSON.stringify(base);
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Collectables</title>
<meta http-equiv="refresh" content="0; url=${base}">
<script>
(function () {
  try {
    sessionStorage.setItem(${storageKey}, location.pathname + location.search + location.hash);
  } catch (e) {}
  location.replace(${target});
})();
</script>
</head>
<body></body>
</html>
`;
}

export function injectSpaRestoreScript(html: string): string {
  if (html.includes(SPA_RESTORE_SCRIPT_MARKER)) return html;
  const storageKey = JSON.stringify(SPA_REDIRECT_STORAGE_KEY);
  const script = `<script ${SPA_RESTORE_SCRIPT_MARKER}>
(function () {
  try {
    var key = ${storageKey};
    var redirect = sessionStorage.getItem(key);
    if (!redirect) return;
    sessionStorage.removeItem(key);
    var current = location.pathname + location.search + location.hash;
    if (redirect !== current && redirect.charAt(0) === "/") {
      history.replaceState(null, "", redirect);
    }
  } catch (e) {}
})();
</script>`;
  if (html.includes("</head>")) {
    return html.replace("</head>", `${script}</head>`);
  }
  return script + html;
}

/**
 * Service-worker source. `version` should change whenever the deployed bundle
 * changes (the build script passes a hash of the patched index.html) so a
 * redeploy busts the cached shell and the fallback never points at stale,
 * since-deleted hashed JS chunks.
 *
 * Strategy: only same-origin GET navigations are intercepted, network-first.
 * - 2xx  → return it; refresh the cached shell when it's the app shell itself.
 * - 404  → GitHub Pages couldn't resolve a dynamic route; serve the cached
 *          shell with 200 so Safari never sees the 404 (the actual fix).
 * - throw → offline; serve the cached shell if we have one.
 * Asset requests are left untouched (pass straight through to the network).
 */
export function buildServiceWorker(baseUrl: string, version: string): string {
  const base = normalizeSpaBaseUrl(baseUrl);
  const shell = JSON.stringify(base + "index.html");
  const baseLiteral = JSON.stringify(base);
  const cacheName = JSON.stringify(
    "collectables-spa-" + (version || "dev"),
  );
  return `// Generated by scripts/build-spa-fallback.ts — do not edit by hand.
var CACHE = ${cacheName};
var BASE = ${baseLiteral};
var SHELL = ${shell};

self.addEventListener("install", function (event) {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE).then(function (cache) {
      return cache.add(new Request(SHELL, { cache: "reload" }));
    }).catch(function () {})
  );
});

self.addEventListener("activate", function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys.map(function (k) {
          return k === CACHE ? null : caches.delete(k);
        })
      );
    }).then(function () {
      return self.clients.claim();
    })
  );
});

self.addEventListener("fetch", function (event) {
  var req = event.request;
  if (req.method !== "GET") return;
  if (req.mode !== "navigate") return;
  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname.indexOf(BASE) !== 0) return;

  event.respondWith(
    fetch(req).then(function (res) {
      if (res && res.status === 404) {
        return caches.match(SHELL).then(function (cached) {
          return cached || res;
        });
      }
      if (res && res.ok && url.pathname === BASE) {
        var copy = res.clone();
        caches.open(CACHE).then(function (cache) {
          cache.put(SHELL, copy);
        }).catch(function () {});
      }
      return res;
    }).catch(function () {
      return caches.match(SHELL).then(function (cached) {
        if (cached) return cached;
        return Response.error();
      });
    })
  );
});
`;
}

export function injectServiceWorkerRegistration(
  html: string,
  baseUrl: string,
): string {
  if (html.includes(SPA_SW_REGISTER_MARKER)) return html;
  const base = normalizeSpaBaseUrl(baseUrl);
  const swUrl = JSON.stringify(base + SERVICE_WORKER_FILENAME);
  const scope = JSON.stringify(base);
  const script = `<script ${SPA_SW_REGISTER_MARKER}>
(function () {
  if (!("serviceWorker" in navigator)) return;
  var h = location.hostname;
  var secure = location.protocol === "https:" || h === "localhost" || h === "127.0.0.1";
  if (!secure) return;
  window.addEventListener("load", function () {
    try {
      navigator.serviceWorker.register(${swUrl}, { scope: ${scope} }).catch(function () {});
    } catch (e) {}
  });
})();
</script>`;
  if (html.includes("</head>")) {
    return html.replace("</head>", `${script}</head>`);
  }
  return script + html;
}
